version: "3.2"

services:
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
#    volumes:
#      - "/c/Users/SharonMai/mysql_data:/var/lib/mysql"
    env_file: .env.prod

  web:
    image: ppp300a/prj_dept-web:1.0.0
    container_name: dept-web
    env_file: .env.prod  # 從.env文件加載環境變量
    environment:
      - PYTHONPATH=/data/prj_dept  # 當項目結構非django預設時需要使用
      - DJANGO_SETTINGS_MODULE=settings.local  # 告诉 Django 和 uWSGI 使用哪个设置文件
    entrypoint: [ "/bin/sh", "/data/prj_dept/start.prod.sh" ]  # 容器啟動後執行的命令
    volumes:
      - staticfiles-data:/data/prj_dept/staticfiles
    ports:
      - "8000:8000"
    depends_on: # 設定服務的啟動順序
      - mysql
      - redis
      - celery

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: ppp300a/prj_dept-nginx:1.0.0
    volumes:
      - staticfiles-data:/var/prj_dept/staticfiles
    ports:
      - "0.0.0.0:80:80"

  redis:
    image: "redis:alpine"
    env_file: .env.prod
    ports:
      - "6379:6379"

  celery:
    image: ppp300a/prj_dept-web:1.0.0
    env_file: .env.prod
#    volumes:
#      - shared_jenkins_home:/workspace/prj_dept-test:/data/prj_dept
#      - /data/logs/prj_dept/:/data/logs/prj_dept/  # 把日誌映射到主機的指定路徑以便查看和持久化
    entrypoint: [ "/bin/sh", "/data/prj_dept/NotUse.worker.start.sh" ]
    depends_on:
      - redis




volumes:
  staticfiles-data:
