version: "3.2"

services:
  mysql:
    image: ppp300a/mysql:1.7.0
    container_name: dept-mysql
    ports:
      - "3306:3306"
#    volumes:
#      - "/c/Users/SharonMai/mysql_data:/var/lib/mysql"
    env_file: .env.prod

  web:
    image: ppp300a/web:1.7.0
    container_name: dept-web
    env_file: .env.prod  # 從.env文件加載環境變量
    environment:
      - PYTHONPATH=/data/prj_dept  # 當項目結構非django預設時需要使用
      - DJANGO_SETTINGS_MODULE=settings.local  # 告诉 Django 和 uWSGI 使用哪个设置文件
    entrypoint: [ "/bin/sh", "/data/prj_dept/start.prod.sh" ]  # 容器啟動後執行的命令
    volumes:
      - staticfiles-local:/data/prj_dept/staticfiles
    ports:
      - "8000:8000"
    depends_on: # 設定服務的啟動順序
      - mysql
      - redis
      - celery

  redis:
    image: ppp300a/redis:1.7.0
    container_name: dept-redis
    env_file: .env.prod
    ports:
      - "6379:6379"

  celery:
    image: ppp300a/celery:1.7.0
    container_name: dept-celery
    env_file: .env.prod
#    volumes:
#      - shared_jenkins_home:/workspace/prj_dept-test:/data/prj_dept
#      - /data/logs/prj_dept/:/data/logs/prj_dept/  # 把日誌映射到主機的指定路徑以便查看和持久化
    entrypoint: [ "/bin/sh", "/data/prj_dept/worker.start.sh" ]
    depends_on:
      - redis

  nginx:
    image: ppp300a/nginx:1.7.0
    container_name: dept-nginx
    volumes:
      - staticfiles-local:/var/prj_dept/staticfiles
    command: [ nginx-debug, '-g', 'daemon off;' ]
    ports:
      - "192.168.1.103:80:80"


volumes:
  staticfiles-local:
