version: "3.11"

services:
  ngrok_jenkins:
    image: ngrok/ngrok
    container_name: jenkins_ngrok
    env_file: .env.test
    command:
      - "tunnel"
      - "--region=us"
      - "--label"
      - "edge=edghts_2SNk363rvTx8UIR6Rbj9eF0oq7G"
      - "http://nginx:80"
    ports:
      - "4040:4040"


  nginx:
    image: ppp300a/prj_dept-nginx-test:1.0.1
    build:
      context: .
      dockerfile: Dockerfile.nginx.test
    volumes:
      - staticfiles-data:/var/prj_dept/staticfiles
    entrypoint: [ "nginx", "-g", "daemon off;" ]
    depends_on:
      web:
        condition: service_healthy
    ports:
      - "80:80"


  mysql:
    image: ppp300a/prj_dept-mysql8-test:1.0.1
    build:
      context: .
      dockerfile: Dockerfile.mysql8
    env_file: .env.test
    volumes:
      - "/c/Users/SharonMai/mysql_data:/var/lib/mysql"
    entrypoint: ["/usr/local/bin/mysql8-init.sh"]
    ports:
      - "3306:3306"


  web:
    image: ppp300a/prj_dept-web-test:1.0.1
    build:
      context: .  # Dockerfile的位置
      dockerfile: Dockerfile.test
    env_file: .env.test  # 從.env文件加載環境變量
    environment:
      - PYTHONPATH=/data/prj_dept  # 當項目結構非django預設時需要使用
      - DJANGO_SETTINGS_MODULE=settings.prod  # 告诉 Django 使用哪个设置文件
    volumes:
      - staticfiles-data:/data/prj_dept/staticfiles
    entrypoint: [ "/bin/sh", "/data/prj_dept/start.prod.sh" ]  # 容器啟動後執行的命令
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: [ "CMD", "python", "-c", "import http.client; conn = http.client.HTTPConnection('localhost', 8000); conn.request('HEAD', '/'); res = conn.getresponse();" ]
      interval: 60s
      timeout: 15s
      retries: 5
    ports:
      - "8000:8000"


  redis:
    image: "redis:7.2.2-alpine3.18"
    env_file: .env.test
    ports:
      - "6379:6379"


  celery_worker:
    image: ppp300a/prj_dept-web-test:1.0.1
    build:
      context: .  # Dockerfile的位置
      dockerfile: Dockerfile.test
    env_file: .env.test
    environment:
      - PYTHONPATH=/data/prj_dept  # 當項目結構非django預設時需要使用
      - DJANGO_SETTINGS_MODULE=settings.prod  # 告诉 Django 使用哪个设置文件
    command: celery -A prj_dept.celery:app worker --loglevel=info
    depends_on:
      - redis
      - web


  flower:
    image: mher/flower
    command: celery --broker=redis://redis:6379/1 flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis


volumes:
  staticfiles-data:
    external: true
    name:  staticfiles-data
