version: "3.2"
services:
  mysql:
    image: "mysql:8.0"
    container_name: dept-mysql
    ports:
      - "3306:3306"
    volumes:
      - "/c/Users/SharonMai/mysql_data:/var/lib/mysql"
    env_file: .env.docker

  web:
    image: ppp300a/prj_dept-test:1.6.0
    container_name: dept-web
    build:
      context: .  # Dockerfile的位置
      dockerfile: Dockerfile
    env_file: .env.docker  # 從.env文件加載環境變量
    environment:
      - DOCKER_ENV=True  # 跟django交互判斷引用哪個.env文件
      - server_params=--settings=settings.local  # 添加額外的環境變量
    entrypoint: [ "/bin/sh", "/data/prj_dept/start.local.sh" ]  # 容器啟動後執行的命令

    volumes:
      - jenkins_home-test:/data/prj_dept
#      - jenkins_home:/var/jenkins_home/workspace/prj_dept-test:/data/prj_dept-test
#    volumes:
#      - jenkins_home:/var/jenkins_home  # 映射當前本機路徑，達到自動更新加載改過的代碼
        # 把日誌映射到主機的指定路徑以便查看和持久化
    ports:
      - "8000:8000"
    depends_on: # 設定服務的啟動順序
      - mysql
      - redis
      - celery
      - flower


  redis:
    image: "redis:alpine" # or replace with your own Redis image
    container_name: dept-redis
    env_file: .env.docker
    ports:
      - "6379:6379"
  celery:
    build:
      context: .  # Dockerfile的位置
      dockerfile: Dockerfile
    container_name: dept-celery
    env_file: .env.docker
    volumes:
      - jenkins_home-test:/data/prj_dept
      - /data/logs/prj_dept/:/data/logs/prj_dept/  # 把日誌映射到主機的指定路徑以便查看和持久化
    command: /bin/sh /data/prj_dept/worker.start.sh
    depends_on:
      - redis
  flower:
    build:
      context: .  # Dockerfile的位置
      dockerfile: Dockerfile
    container_name: dept-flower
    ports:
      - "5555:5555"
    volumes:
      - jenkins_home-test:/data/prj_dept
      - /data/logs/prj_dept/:/data/logs/prj_dept/
    entrypoint: ["/bin/sh", "/data/prj_dept/flower.start.sh"]
    depends_on:
      - redis

volumes:
  jenkins_home-test: