version: "3.2"

services:
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    volumes:

      - mysql-data:/var/lib/mysql
 #     - logs:/data/logs/mysql # 日誌映射
    env_file: .env.prod

  web:
    image: ppp300a/prj_dept-web:1.0.0
    container_name: dept-web
    env_file: .env.prod
    environment:
      - PYTHONPATH=/data/prj_dept
      - DJANGO_SETTINGS_MODULE=settings.local
    entrypoint: [ "/bin/sh", "/data/prj_dept/start.prod.sh" ]
    volumes:
      - staticfiles-data:/data/prj_dept/staticfiles
#      - logs:/data/logs/web # 日誌映射
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
      - celery
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001')" ]
      interval: 10s
      timeout: 5s
      retries: 5


  nginx:
    image: ppp300a/prj_dept-nginx:1.0.0
    volumes:
      - staticfiles-data:/var/prj_dept/staticfiles
#      - logs:/data/logs/nginx # 日誌映射
    entrypoint: [ "nginx", "-g", "daemon off;" ]
    restart: on-failure:5
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      web:
        condition: service_healthy

  redis:
    image: "redis:alpine"
    env_file: .env.prod
#    volumes:
#      - logs:/data/logs/redis # 日誌映射
    ports:
      - "6379:6379"

  celery:
    image: ppp300a/prj_dept-web:1.0.0
    env_file: .env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=settings.local
#    volumes:
#      - "logs:/data/logs/celery" # 日誌映射
    command: [ "celery", "-A", "prj_dept", "worker", "-l", "INFO", "-P", "solo" ]
    depends_on:
      - redis


volumes:
  staticfiles-data:
    name: staticfiles-data
  mysql-data:
    name: mysql-data
#  logs: # 日誌存儲卷
#    name: logs
