version: "3.2"
services:
  mysql:
    image: "mysql:8.0"
    container_name: dept-mysql
    ports:
      - "3306:3306"
    volumes:
      - "/c/Users/SharonMai/mysql_data:/var/lib/mysql"
    env_file: .env.docker

  web:
    build:
      context: .  # Dockerfile的位置
    image: ppp300a/prj_dept-test:1.7.0
    container_name: dept-web
    env_file: .env.docker  # 從.env文件加載環境變量
    environment:
      - PYTHONPATH=/data/prj_dept  # 當項目結構非django預設時需要使用
      - DJANGO_SETTINGS_MODULE=settings.local  # 告诉 Django 和 uWSGI 使用哪个设置文件
#      - server_params=--settings=settings.local  # 给 manage.py 命令用的
    entrypoint: [ "/bin/sh", "/data/prj_dept/start.prod.sh" ]  # 容器啟動後執行的命令
    volumes:
      - staticfiles-local:/data/prj_dept/staticfiles
    ports:
      - "8000:8000"
    depends_on: # 設定服務的啟動順序
      - mysql
      - redis
      - celery

  redis:
    image: "redis:alpine" # or replace with your own Redis image
    env_file: .env.docker
    ports:
      - "6379:6379"

  celery:
    image: ppp300a/prj_dept-test:1.7.0
    env_file: .env.docker
    environment:
      - DJANGO_SETTINGS_MODULE=settings.local
    command: ["celery", "-A", "prj_dept", "worker", "-l", "INFO", "-P", "solo"]
    depends_on:
      - redis

  nginx:
    image: custom-nginx:latest
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - staticfiles-local:/var/prj_dept/staticfiles
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    ports:
      - "192.168.1.103:80:80"


volumes:
  staticfiles-local:
  shared_jenkins_home:
    external: true
    name:  jenkins_home