version: "3.2"
services:
  mysql:
    image: "mysql:8.0"
    container_name: dept-mysql
    ports:
      - "3306:3306"
    volumes:
      - "/c/Users/SharonMai/mysql_data:/var/lib/mysql"
    env_file: .env.docker

  web:
    build:
      context: .  # Dockerfile的位置
    image: ppp300a/prj_dept-test:1.7.0
    container_name: dept-web
    env_file: .env.docker  # 從.env文件加載環境變量
    environment:
      - server_params=--settings=settings.local  # 添加額外的環境變量
    entrypoint: [ "/bin/sh", "/data/prj_dept/start.prod.sh" ]  # 容器啟動後執行的命令
    #權限問題添加user?
    user: "uwsgiuser:uwsgi"
    volumes:
      - staticfiles-local:/data/prj_dept/staticfiles
#      - staticfiles-local:/data/prj_dept/nginx.conf
    ports:
      - "8000:8000"
    depends_on: # 設定服務的啟動順序
      - mysql
      - redis
      - celery

  redis:
    image: "redis:alpine" # or replace with your own Redis image
    container_name: dept-redis
    env_file: .env.docker
    ports:
      - "6379:6379"

  celery:
    build:
      context: .  # Dockerfile的位置
    container_name: dept-celery
    env_file: .env.docker
#    volumes:
#      - shared_jenkins_home:/workspace/prj_dept-test:/data/prj_dept
#      - /data/logs/prj_dept/:/data/logs/prj_dept/  # 把日誌映射到主機的指定路徑以便查看和持久化
    entrypoint: [ "/bin/sh", "/data/prj_dept/worker.start.sh" ]
    depends_on:
      - redis

  nginx:
    image: custom-nginx:latest
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - staticfiles-local:/var/prj_dept/staticfiles
    command: [ nginx-debug, '-g', 'daemon off;' ]
    ports:
      - "192.168.1.103:80:80"


volumes:
  staticfiles-local:
  shared_jenkins_home:
    external: true
    name:  jenkins_home