# 使用輕量級的 Python 鏡像
FROM python:3.9-alpine

# 設置工作目錄
WORKDIR /data/prj_dept


# 複製 requirements-dev.txt 並安裝必要的包和庫，然後清理
COPY requirements-dev.txt ./
RUN apk update && \
    apk add --no-cache gcc musl-dev libffi-dev mariadb-connector-c-dev gettext && \
    python3 -m pip install --upgrade pip && \
    pip install -r requirements-dev.txt && \
    pip install uwsgi && \
    apk del gcc musl-dev libffi-dev && \
    rm -rf /var/cache/apk/* && \
    ln -sf /usr/share/zoneinfo/Asia/Taipei /etc/localtime && \
    echo 'Asia/Taipei' >/etc/timezone


# 將當前目錄（即 Dockerfile 所在的目錄）下的所有文件和子目錄複製到 WORKDIR 路徑中
#COPY . .

# 設置執行權限
RUN chmod +x /data/prj_dept/start.dev.sh

# 暴露端口
EXPOSE 8000
