version: "3.2"
services:
  mysql:
    image: "mysql:8.0"
    container_name: dev-mysql
    volumes:
      - /c/Users/SharonMai/mysql_data:/var/lib/mysql
    env_file: .env.dev
    ports:
      - "3306:3306"

#  web:
#    image: ppp300a/prj_dept-dev:1.0.0
#    container_name: dev-web
#    build:
#      context: .  # Dockerfile的位置
#      dockerfile: Dockerfile.dev
#    env_file: .env.dev  # 從.env文件加載環境變量
#    environment:
#      - DJANGO_SETTINGS_MODULE=settings.dev
#      - DJANGO_ENV=dev
#    command: [ "/bin/sh", "/data/prj_dept/start.dev.sh" ]  # 容器啟動後執行的命令
#    volumes:
#      - .:/data/prj_dept  # 映射當前本機路徑，達到自動更新加載改過的代碼
#      - /data/logs/prj_dept/:/data/logs/prj_dept/  # 把日誌映射到主機的指定路徑以便查看和持久化
#    ports:
#      - "8000:8000"
#    depends_on:
#      - mysql
#      - redis
#      - celery
#      - flower


  redis:
    image: "redis:alpine" # or replace with your own Redis image
    container_name: dev-redis
    env_file: .env.dev
    ports:
      - "6379:6379"

  celery:
    image: ppp300a/prj_dept-dev:1.0.0
    container_name: dev-celery
    env_file: .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=settings.dev
    volumes:
      - .:/data/prj_dept
      - /data/logs/prj_dept/:/data/logs/prj_dept/  # 把日誌映射到主機的指定路徑以便查看和持久化
    command: [ "celery", "-A", "prj_dept", "worker", "-l", "INFO", "-P", "solo" ]
    depends_on:
      - redis

  flower:
    image: ppp300a/prj_dept-dev:1.0.0
    container_name: dev-flower
    ports:
      - "5555:5555"
    environment:
      - DJANGO_SETTINGS_MODULE=settings.dev
    volumes:
      - .:/data/prj_dept
      - /data/logs/prj_dept/:/data/logs/prj_dept/
    entrypoint: [ "/bin/sh", "/data/prj_dept/flower.start.sh" ]
    depends_on:
      - celery
