version: "3.8"

services:
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-logs:/var/log/mysql
      - ./mysql8-init.sh:/usr/local/bin/mysql8-init.sh
    env_file: .env.prod
    entrypoint: ["/usr/local/bin/mysql8-init.sh"]
    command:
      - "--max-connections=200"
      - "--slow-query-log=1"
      - "--long-query-time=2"
      - "--log-error=/var/log/mysql/mysql_error.log"
      - "--slow-query-log-file=/var/log/mysql/mysql_slow.log"


  web:
    image: ppp300a/prj_dept-web:1.0.0
    container_name: dept-web
    user: 'uwsgiuser:uwsgi'
    build:
      context: .  # Dockerfile的位置
      dockerfile: Dockerfile
      args:
        DJANGO_SETTINGS_MODULE: settings.prod
    env_file: .env.prod
    environment:
      - PYTHONPATH=/data/prj_dept
      - DJANGO_SETTINGS_MODULE=settings.prod
    entrypoint: [ "/bin/sh", "/data/prj_dept/start.prod.sh" ]
    volumes:
      - staticfiles-data:/data/prj_dept/staticfiles  # 提供給 nginx 靜態文件讀取使用
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
#      - celery
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: ppp300a/prj_dept-nginx:1.0.0
    entrypoint: [ "nginx", "-g", "daemon off;" ]
    volumes:
      - staticfiles-data:/var/prj_dept/staticfiles
    depends_on:
      web:
        condition: service_healthy
    env_file: .env.prod
    ports:
      - "${INTERNAL_NGINX_DOMAIN}"

  redis:
    image: "redis:alpine"
    env_file: .env.prod
    ports:
      - "6379:6379"

#  celery:
#    image: ppp300a/prj_dept-web:1.0.0
#    env_file: .env.prod
#    environment:
#      - DJANGO_SETTINGS_MODULE=settings.prod
##    volumes:
##      - "logs:/data/logs/celery" # 日誌映射
#    command: [ "celery", "-A", "prj_dept", "worker", "-l", "INFO", "-P", "solo" ]
#    depends_on:
#      - redis


volumes:
  staticfiles-data:
    external: true
    name: staticfiles-data
  mysql-data:
    external: true
    name: mysql-data
  mysql-logs:
    external: true
    name: mysql-logs
