version: '3'
services:
  prj_dept-web-1:
    image: ppp300a/prj_dept-web
    entrypoint: ["/bin/sh", "/data/prj_dept/start.local.sh"]
    environment:
      - server_params=--settings=settings.local
    volumes:
      - .:/data/prj_dept
      - /data/logs/prj_dept/
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
      - celery
      - flower
  mysql:
    image: "mysql:latest"
    container_name: dept-mysql
    ports:
      - "3306:3306"
    volumes:
      - "/home/ubuntu/mysql_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redis:
    image: "redis:alpine" # or replace with your own Redis image
    container_name: dept-redis
    ports:
      - "6379:6379"
  celery:
    image: "celery:latest"
    container_name: dept-celery
    volumes:
      - .:/data/prj_dept
      - /home/ubuntu/log:/data/logs/prj_dept/
    entrypoint: ["/bin/sh", "/data/prj_dept/worker.start.sh"]
    depends_on:
      - redis
  flower:
    image: "mher/flower:latest"
    container_name: dept-flower
    ports:
      - "5555:5555"
    volumes:
      - .:/data/prj_dept
      - /home/ubuntu/log:/data/logs/prj_dept/
    entrypoint: ["/bin/sh", "/data/prj_dept/flower.start.sh"]
    depends_on:
      - redis

