version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      - TZ=Asia/Taipei
      - JAVA_OPTS=-Duser.timezone=Asia/Taipei
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always
volumes:
  jenkins_home:
