version: '3.7'
services:
  jenkins:
    build:
      context: .  # Dockerfile的位置
      dockerfile: jenkins-Dockerfile
    environment:
      - TZ=Asia/Taipei
      - JAVA_OPTS=-Duser.timezone=Asia/Taipei
      - SSH_CONFIG_FILE=/var/jenkins_home/.ssh/config
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home  # 持久化數據
      - /var/run/docker.sock:/var/run/docker.sock  # 掛載本機 Docker 到 Jenkins 容器中使用
      - /c/Users/SharonMai/.ssh:/var/jenkins_home/.ssh  # 讓jenkins使用SSH私鑰
      - ./.env.docker:/var/jenkins_home/workspace/prj_dept-test/.env.docker  # 新增的映射
    restart: always
volumes:
  jenkins_home:
