apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    app: celery
  name: dept-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: celery
    spec:
      containers:
        - command:
            - /bin/sh
            - /data/prj_dept/NotUse.worker.start.sh
          env:
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  key: ALLOWED_HOSTS
                  name: dept-secrets
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  key: CELERY_BROKER_URL
                  name: dept-secrets
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  key: CELERY_RESULT_BACKEND
                  name: dept-secrets
            - name: LINE_CHANNEL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: LINE_CHANNEL_ACCESS_TOKEN
                  name: dept-secrets
            - name: LINE_CHANNEL_SECRET
              valueFrom:
                secretKeyRef:
                  key: LINE_CHANNEL_SECRET
                  name: dept-secrets
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  key: MYSQL_HOST
                  name: dept-secrets
            - name: MYSQL_NAME
              valueFrom:
                secretKeyRef:
                  key: MYSQL_NAME
                  name: dept-secrets
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: dept-secrets
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PORT
                  name: dept-secrets
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: dept-secrets
            - name: REDIS_LOCATION
              valueFrom:
                secretKeyRef:
                  key: REDIS_LOCATION
                  name: dept-secrets
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: dept-secrets
          image: celery
          name: dept-celery
          resources: {}
          volumeMounts:
            - mountPath: /data/prj_dept
              name: celery-claim0
            - mountPath: /data/logs/prj_dept
              name: celery-claim1
      restartPolicy: Always
      volumes:
        - name: celery-claim0
          persistentVolumeClaim:
            claimName: celery-claim0
        - name: celery-claim1
          persistentVolumeClaim:
            claimName: celery-claim1

