apiVersion: apps/v1
kind: Deployment
metadata:
  name: dept-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: dept-mysql
          env:
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  key: ALLOWED_HOSTS
                  name: dept-secrets
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  key: CELERY_BROKER_URL
                  name: dept-secrets
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  key: CELERY_RESULT_BACKEND
                  name: dept-secrets
            - name: LINE_CHANNEL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: LINE_CHANNEL_ACCESS_TOKEN
                  name: dept-secrets
            - name: LINE_CHANNEL_SECRET
              valueFrom:
                secretKeyRef:
                  key: LINE_CHANNEL_SECRET
                  name: dept-secrets
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  key: MYSQL_HOST
                  name: dept-secrets
            - name: MYSQL_NAME
              valueFrom:
                secretKeyRef:
                  key: MYSQL_NAME
                  name: dept-secrets
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: dept-secrets
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PORT
                  name: dept-secrets
            - name: REDIS_LOCATION
              valueFrom:
                secretKeyRef:
                  key: REDIS_LOCATION
                  name: dept-secrets
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: dept-secrets
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-claim0
      restartPolicy: Always
      volumes:
        - name: mysql-claim0
          persistentVolumeClaim:
            claimName: mysql-claim0
status: {}
