apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - command: ["/bin/sh", "/data/prj_dept/start.local.sh"]
          env:
            - name: server_params
              value: "--settings=settings.local"
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  key: ALLOWED_HOSTS
                  name: dept-secrets
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  key: CELERY_BROKER_URL
                  name: dept-secrets
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  key: CELERY_RESULT_BACKEND
                  name: dept-secrets
            - name: DOCKER_ENV
              value: "True"
            - name: LINE_CHANNEL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: LINE_CHANNEL_ACCESS_TOKEN
                  name: dept-secrets
            - name: LINE_CHANNEL_SECRET
              valueFrom:
                secretKeyRef:
                  key: LINE_CHANNEL_SECRET
                  name: dept-secrets
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  key: MYSQL_HOST
                  name: dept-secrets
            - name: MYSQL_NAME
              valueFrom:
                secretKeyRef:
                  key: MYSQL_NAME
                  name: dept-secrets
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: dept-secrets
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PORT
                  name: dept-secrets
            - name: REDIS_LOCATION
              valueFrom:
                secretKeyRef:
                  key: REDIS_LOCATION
                  name: dept-secrets
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: dept-secrets
          image: ppp300a/dept-dev:1.2.0
          name: web
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "500Mi"
          volumeMounts:
            - mountPath: /data/logs/prj_dept
              name: web-claim0
      restartPolicy: Always
      volumes:
        - name: web-claim0
          persistentVolumeClaim:
            claimName: web-claim0
status: {}