# Generated by Django 4.1.3 on 2023-09-07 22:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='帳號名')),
                ('password', models.CharField(max_length=512, verbose_name='密碼')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='信箱')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='部門')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('upload_data', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手機號碼')),
                ('price', models.IntegerField(default=0, verbose_name='費用')),
                ('level', models.SmallIntegerField(choices=[(1, '一級'), (2, '二級'), (3, '三級')], verbose_name='級別')),
                ('status', models.SmallIntegerField(choices=[(1, '已佔用'), (2, '未占用')], default=2, verbose_name='占用')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, '重要'), (2, '普通'), (3, '閒置')], default=1, verbose_name='級別')),
                ('title', models.CharField(max_length=64, verbose_name='標題')),
                ('detail', models.TextField(verbose_name='詳細訊息')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密碼')),
                ('birthday', models.DateField(default='2000-01-01', verbose_name='生日')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='帳號餘額')),
                ('create_time', models.DateField(verbose_name='就職時間')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性別')),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dept_app.department', verbose_name='部門')),
            ],
        ),
    ]
