# Generated by Django 4.1.3 on 2023-06-17 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user_name',
            new_name='username',
        ),
    ]
