# Generated by Django 4.1.3 on 2023-09-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=512, null=True, verbose_name='密碼'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=512, verbose_name='帳號名'),
        ),
    ]
