# Generated by Django 4.1.3 on 2023-09-12 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept_app', '0002_admin_email_token_admin_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email_token',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='is_verified',
        ),
    ]
