# Generated by Django 4.1.3 on 2023-11-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_app', '0002_mobilenum_delete_prettynum_remove_userinfo_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='信箱'),
        ),
    ]
