# Generated by Django 4.1.3 on 2023-09-12 01:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dept_app', '0003_remove_admin_email_token_remove_admin_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email_token',
            field=models.UUIDField(default=uuid.UUID('8257e95d-f5ec-4f78-8225-0e57cddb76dd'), editable=False, verbose_name='驗證碼'),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='驗證已確認'),
        ),
    ]
