# Generated by Django 4.1.3 on 2023-09-12 01:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dept_app', '0004_admin_email_token_admin_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email_token',
            field=models.UUIDField(default=uuid.UUID('7c098b0e-072e-467e-a262-800d54e4e7b2'), editable=False, verbose_name='驗證碼'),
        ),
    ]
