# Generated by Django 4.1.3 on 2023-09-12 06:50

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dept_app', '0005_alter_admin_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 6, 50, 50, 690631, tzinfo=datetime.timezone.utc), verbose_name='驗證碼期限'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email_token',
            field=models.UUIDField(default=uuid.UUID('6718003b-a445-4edc-a082-9e7021815854'), editable=False, verbose_name='驗證碼'),
        ),
    ]
