# Generated by Django 4.1.3 on 2023-09-13 13:41

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dept_app', '0006_admin_token_expiration_alter_admin_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='驗證碼'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 16, 13, 41, 45, 775369, tzinfo=datetime.timezone.utc), verbose_name='驗證碼期限'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=512, verbose_name='用戶名'),
        ),
    ]
