# Generated by Django 4.1.3 on 2023-09-16 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_app', '0007_alter_admin_email_token_alter_admin_token_expiration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prettynum',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='account',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
        migrations.AddField(
            model_name='prettynum',
            name='brand',
            field=models.SmallIntegerField(choices=[(1, 'iPhone 15'), (2, 'iPhone 15 Pro'), (3, 'iPhone 14')], default=1, verbose_name='品牌'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='quota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='進修額度(美金)'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 19, 37, 1, 691960, tzinfo=datetime.timezone.utc), verbose_name='驗證碼期限'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='price',
            field=models.IntegerField(default=0, verbose_name='電信費'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已出借'), (2, '未出借')], default=2, verbose_name='出借'),
        ),
    ]
