# Generated by Django 4.1.3 on 2023-09-16 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_app', '0008_remove_prettynum_level_remove_userinfo_account_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrettyNum',
            new_name='MobileNum',
        ),
        migrations.AlterField(
            model_name='admin',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 20, 34, 27, 644135, tzinfo=datetime.timezone.utc), verbose_name='驗證碼期限'),
        ),
    ]
