version: "3.8"

services:
  loki:
    image: grafana/loki:2.8.4
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-files:/loki
    ports:
      - "3100:3100"
    networks:
      - PLG_network
    restart: unless-stopped


  promtail:
    image: grafana/promtail:2.8.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.prod.yaml:/etc/promtail/docker-config.yaml
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - PLG_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana-enterprise:10.1.4
    volumes:
      - grafana-board:/var/lib/grafana
    env_file: .env.prod
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=True
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SERVER_ROOT_URL=http://localhost:3000
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    ports:
      - "3000:3000"
    networks:
      - PLG_network
      - grafana_nginx_proxy_network
    restart: unless-stopped

volumes:
  loki-files:
    external: true
    name: loki-files
  grafana-board:
    external: true
    name: grafana-board

networks:
  PLG_network:
    external: true
    name: PLG_network
  grafana_nginx_proxy_network:
    external: true
    name: grafana_nginx_proxy_network
