server:
  http_listen_port: 9080
  grpc_listen_port: 0

# Positions
positions:
  filename: /tmp/positions.yaml

# Loki服务器的地址，修改IP和端口即可，后面Grafana要从这个地方取数据
clients:
  - url: http://loki:3100/loki/api/v1/push  # 因使用docker-compose啟動故修改為服務器名稱

# 数据抓取配置
scrape_configs:
  - job_name: devops        # 任务名称，应该具有唯一性
    static_configs:
      - targets:
          - localhost           # 抓取目标，本地
        labels:
          job: devops       # 标签名，用于筛选数据，最好取一个易于识别的名称
          __path__: /var/log/*.log    # 修改為容器內的日誌位置。收集日志的路径，“*”是通配符，支持正则匹配
  - job_name: mysql_logs
    static_configs:
        - targets: [ 'dev-mysql' ]  # MySQL 容器的名稱
          labels:
            job: mysql_logs
            __path__: /var/log/mysql/*.log  # MySQL 容器內的日誌路徑
    pipeline_stages:
      - multiline:
          firstline: '^\[[a-f0-9]{32}]*'
          max_wait_time: 3s
