version: "3.2"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.8.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.8.4
    volumes:
      - ./log:/var/log/
      - ./promtail-config.yaml:/etc/promtail/docker-config.yaml
      - ./positions.yaml:/tmp/positions.yaml
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - loki
      - shared-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki


